### ISSUE TITLE
Alerts with the same text get stacked on top of each other

### ISSUE THREAD

**Issue by aalaap** [OzyAst/Hullabaloo#1]
The following code produces three separate notifications:

    $.hulla.send("Lorem", "success");
    $.hulla.send("Ipsum", "info");
    $.hulla.send("Dolor", "warning");

However, the following code will stack all three notifications on top of each other since they're the same:

    $.hulla.send("Lorem", "success");
    $.hulla.send("Lorem", "success");
    $.hulla.send("Lorem", "success");

How can the three be shown as separate notifications in spite of the text being the same? A good use case is a notification like "Updated!", which will be the same even if the update takes place five times. Also, #2 setting the `stack_spacing` seems to have no effect.

**Comment by OzyAst** [comment]
Принудительная отмена группировки
$.hulla.send("message", "success", 0);

Добавил дополнительную опцию, которая отменяет группировку
