### ISSUE TITLE
Initialization options are not used by the script object

### ISSUE THREAD

**Issue by aalaap** [OzyAst/Hullabaloo#2]
I'm using the following code to initialize the Hullabaloo object, but it has no effect:

    $.hulla = new hullabaloo({
        offset: {
            from: "top",
            amount: 200
        },
    });

Changing the value of `amount` from 20 to 200 to 2000 has absolutely no effect. Neither does any other option, such as `stackup_spacing`.

**Comment by OzyAst** [comment]
Задаем положение алерта и отступ
$.hulla = new hullabaloo();
$.hulla.options.offset = {
    from: "top",
    amount: 30
};
Задаем расстояние между алертами
$.hulla.options.stackup_spacing = 15;

Ваш вариант конечно удобней. В скором времени постараюсь сделать так как у вас.
Спасибо!
