### ISSUE TITLE
Script error for "buoy", needed by: hullabaloo

### ISSUE THREAD

**Issue by rognales** [OzyAst/Hullabaloo#3]
Hi Dev,

I got this error when loading your library using requireJS. May i know which buoy.js that you require?

**Comment by OzyAst** [comment]
Hi, i do not use buoy.js not enywere

**Comment by rognales** [comment]
But on hullabaloo.js line 9, says it requires 'buoy'

**Comment by OzyAst** [comment]
i'm sorry! fixed, should work
